from __future__ import annotations

from typing import Protocol

from llm_rio.domain import PlacementProfile, WorkerPlacement
from llm_rio.host_memory import (
    HostMemorySample,
)


class WorkerLifecycle(Protocol):
    async def _refresh_cached_worker_samples(self) -> None: ...
    def _host_cache_limit_mib(self, host: HostMemorySample) -> float: ...
    def _host_cache_pressure_reason(
        self, host: HostMemorySample, cache_accounted_mib: float, cache_swap_mib: float = 0.0
    ) -> str | None: ...
    async def host_cache_status(self) -> dict[str, float | str | None]: ...
    async def enforce_host_cache_budget(self, *, incoming_worker_id: str | None = None) -> bool: ...
    def _can_share_gpus(
        self,
        profile: PlacementProfile,
        gpu_uuids: tuple[str, ...],
        overlapping_workers: list[WorkerPlacement],
    ) -> bool: ...
    async def sleep(self, worker_id: str) -> None: ...
    async def _offload(self, worker_id: str) -> None: ...
    async def wake(self, worker_id: str) -> None: ...
    async def _post_engine(
        self, worker: WorkerPlacement, path: str, *, params: dict[str, str] | None = None
    ) -> None: ...
